name: Eleventy Build
on: 
  push:
    branches:
      - main

jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Build
        uses: TartanLlama/actions-eleventy@master
        with:
          args: --output docs
          install_dependencies: true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: docs 
          publish_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
